lib/ex_vote_web/router.ex
defmodule ExVoteWeb.Router do
  use ExVoteWeb, :router

  import ExVoteWeb.Plugs.UserPlugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug CORSPlug, origin: "*", methods: ["GET", "POST", "OPTIONS", "DELETE", "PUT"], headers: [ "Accept", "accept-language","content-language", "last-event-id", "Content-Type", "Authorization","X-Requested-With"]
    plug :accepts, ["json"]
  end

  pipeline :api_auth do
    plug :ensure_token
  end

  scope "/", ExVoteWeb do
    pipe_through :browser # Use the default browser stack

    get "/", ProjectController, :index
    get "/projects/view/:id", ProjectController, :view
    post "/projects/add_user", ProjectController, :add_user
    post "/projects/add_candidate", ProjectController, :add_candidate
    post "/projects/add_user_vote", ProjectController, :add_user_vote
    post "/projects/add_candidate_vote", ProjectController, :add_candidate_vote
    post "/projects/delete_candidate_vote", ProjectController, :delete_candidate_vote

    get "/users/login", UserController, :login
    post "/users/login", UserController, :login

    get "/users/logout", UserController, :logout
  end

  scope "/api", ExVoteWeb, as: :api do
    pipe_through :api

    scope "/users" do
      post "/login", Api.UserController, :login
      post "/register", Api.UserController, :register

      scope "/" do
        pipe_through :api_auth

        get "/token_test", Api.UserController, :token_test
      end
    end

    scope "/projects" do
      resources "/", Api.ProjectController, only: [:index, :show, :create], param: "project_id"
      get "/:project_id/report", Api.ProjectController, :report
      get "/:project_id/tickets", Api.ProjectController, :list_tickets
      get "/:project_id/participations", Api.ProjectParticipationController, :list_participations
      get "/:project_id/participations/candidates", Api.ProjectParticipationController, :list_candidates
      get "/:project_id/participations/users", Api.ProjectParticipationController, :list_users

      scope "/" do
        pipe_through :api_auth

        get "/:project_id/participations/current", Api.ProjectParticipationController, :show_current_participation
        post "/:project_id/participations/current", Api.ProjectParticipationController, :create_current_participation
        put "/:project_id/participations/current", Api.ProjectParticipationController, :update_current_participation
        get "/:project_id/participations/current/votes", Api.ProjectParticipationController, :list_votes
        put "/:project_id/participations/current/votes", Api.ProjectParticipationController, :update_votes
      end
    end
  end

  scope "/api/swagger" do
    forward "/", PhoenixSwagger.Plug.SwaggerUI, otp_app: :ex_vote, swagger_file: "swagger.json"
  end

  scope "/api/redoc" do
    get "/", ExVoteWeb.Api.RedocController, :index
  end

  def swagger_info do
    %{
      info: %{
        version: "1.0",
        title: "ExVote API"
      },
      tags: [
        %{
          name: "Projects",
          description: """
          Project contains information about the lifecycle of a participation project. This resource is the base for all participation endpoints.

          For further informations regarding participations see Participations.
          """
        },
        %{
          name: "Users",
          description: "Users are participants in a project. They can vote for candidates, whereas candidates can vote directly for Tickets (requirements)"
        },
        %{
          name: "Project Participations",
          description: """
          Participation represents the voting process. A Participation is an unique relationship between a user (including candidates) and a project.

          For the users currently participating in the a project see Current Participation.
          """
        },
        %{
          name: "Current Participation",
          description: """
          Current Participation describes the participation of an authenticated user (including candidates) in a project.

          The Participation changes according to the current phase of the project.

          - Users vote for a single candidate during the User phase of the project.

          - Candidate vote for none, one, or several tickets (requirements) during the candidate phase of the project.

          """
        }
      ],
      securityDefinitions: %{
        ApiKey: %{
          type: "apiKey",
          name: "Authorization",
          in: "header",
          description: "Token for API operations"
        }
      },
      security: [
        %{ApiKey: []}
      ]
    }
  end
end

lib/ex_vote_web/views/layout_view.ex
defmodule ExVoteWeb.LayoutView do
  use ExVoteWeb, :view
end

lib/ex_vote_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ExVote</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/bulma.min.css") %>">
    <script defer src="<%= static_path(@conn, "/js/fontawesome.min.js") %>"></script>
  </head>

  <body>
    <nav class="navbar is-spaced has-shadow">
      <div class="container">
        <div class="navbar-brand">
          <div class="navbar-item">
            <a href="<%= project_path(@conn, :index) %>" <h1 class="title">ExVote</h1></a>
          </div>
        </div>
        <div class="navbar-menu">
          <div class="navbar-end">
            <%= if @user do %>
              <div class="navbar-item">
                <span>Hello <%= @user.name %>!</span>
              </div>
            <% end %>
            <div class="navbar-item">
              <%= if @user do %>
                <a href="<%= user_path(@conn, :logout) %>">Logout</a>
              <% else %>
                <a href="<%= user_path(@conn, :login) %>">Login</a>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <section class="section">
      <div class="container">
        <%= if get_flash(@conn, :info) do %>
          <div class="notification is-primary"><%= get_flash(@conn, :info) %></div>
        <% end %>
        <%= if get_flash(@conn, :error) do %>
          <div class="notification is-danger"><%= get_flash(@conn, :error) %></div>
        <% end %>

        <%= render @view_module, @view_template, assigns %>
      </div>
    </section>
  </body>
</html>